### ISSUE TITLE
1.6 uses BSPs?

### ISSUE THREAD

**Issue by waliworld** [MathiasVP/CS#1]
there doesnt seem to be much explanation as to what from the cs16 folder goes in /data/

also I thought cs16 used wads? my copy of 1.6 doesnt use BSPs so im confused

**Comment by MathiasVP** [comment]
I updated the README with a short description of which files are needed.
Oh and cs1.6 totally uses .bsp files :) They're in the maps directory of cs1.6 once downloaded off steam
